# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-25 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='default title', max_length=200, null=True)),
                ('description', models.TextField()),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
