# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-26 17:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190726_1711'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='img',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='file',
            new_name='video',
        ),
    ]
