# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-25 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190725_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.CharField(default='', max_length=500),
        ),
    ]
