# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-26 20:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190726_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='user',
        ),
        migrations.RemoveField(
            model_name='course',
            name='image',
        ),
        migrations.RemoveField(
            model_name='course',
            name='link',
        ),
        migrations.DeleteModel(
            name='Token',
        ),
    ]
