# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-25 19:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190725_1318'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('document', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Departeman',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='description',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='image',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='level',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='link',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='name',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='topics',
        ),
        migrations.AddField(
            model_name='movie',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='via',
            field=models.URLField(blank=True),
        ),
    ]
