# Generated by Django 2.2.3 on 2019-07-26 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190725_2023'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
