# Generated by Django 2.2.3 on 2019-07-26 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_delete_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='text',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='via',
        ),
        migrations.AddField(
            model_name='movie',
            name='author',
            field=models.CharField(default='Author', max_length=100),
        ),
        migrations.AddField(
            model_name='movie',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='duration',
            field=models.DurationField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='level',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='topic',
            field=models.CharField(default='IPDR', max_length=50),
        ),
    ]
