# Generated by Django 2.2.3 on 2019-07-26 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20190726_0740'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='file',
            field=models.FileField(null=True, upload_to='video/'),
        ),
    ]
