# Generated by Django 2.2.3 on 2019-07-26 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_movie_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='default.png', upload_to='images/'),
        ),
    ]
