# Generated by Django 2.2.3 on 2019-07-26 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20190726_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='images/default.jpg', upload_to='images/'),
        ),
    ]
